-- DMS Transport Workspace V1
create extension if not exists pgcrypto;
create table if not exists staff (id uuid primary key default gen_random_uuid(), monday_item_id text unique, name text not null, email text, status text default 'Active', created_at timestamptz default now());
create table if not exists astp_compliance (id uuid primary key default gen_random_uuid(), staff_id uuid references staff(id) on delete cascade, driver_application_url text, child_related_declaration_url text, consent_checks_url text, driver_id_cert_url text, criminal_history_url text, medical_fitness_url text, driving_history_url text, wwc_url text, drivers_licence_url text, support_document_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists vehicles (id uuid primary key default gen_random_uuid(), monday_item_id text unique, rego text unique not null, status text, make_model text, year int, vin text, rego_expiry date, hvis_expiry date, astp_usage text, application_pack_url text, emergency_equipment boolean, epi_pen boolean, warning_signage boolean, notes text, current_odometer bigint, created_at timestamptz default now());
create table if not exists bookings (id uuid primary key default gen_random_uuid(), booking_code text unique not null, monday_item_id text unique, source_form_id text, source_submission_id text, submission_date timestamptz, booking_date date, requested_time time, passenger_name text, passenger_email text, passenger_phone text, pickup_location text, dropoff_location text, return_required boolean, wait_time_minutes int, funding_type text, vehicle_type text, quoted_cost numeric(12,2), driver_id uuid references staff(id), vehicle_id uuid references vehicles(id), status text default 'Pending', notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists vehicle_checks (id uuid primary key default gen_random_uuid(), source_form_id text, source_submission_id text unique, check_type text not null check (check_type in ('pre_start','post_shift')), check_date date, driver_name text, staff_id uuid references staff(id), rego text, vehicle_id uuid references vehicles(id), odometer bigint, comments text, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now());
create table if not exists transfer_logs (id uuid primary key default gen_random_uuid(), source_form_id text, source_submission_id text unique, booking_code text, booking_id uuid references bookings(id), driver_name text, vehicle_used text, passenger_name text, pickup_location text, dropoff_location text, collection_date date, collection_time time, return_booked text, wait_time text, notes text, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now());
create table if not exists incidents (id uuid primary key default gen_random_uuid(), source_form_id text, source_submission_id text unique, incident_code text unique, status text default 'Open', incident_at timestamptz, location text, description text, actions_taken text, participant_name text, staff_name text, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now());
create table if not exists stock_items (id uuid primary key default gen_random_uuid(), monday_item_id text unique, name text not null, mandatory_quantity text, expiry_date date, notes text, created_at timestamptz default now());
create table if not exists jotform_submissions (id uuid primary key default gen_random_uuid(), form_id text not null, submission_id text not null unique, payload jsonb not null, received_at timestamptz not null default now(), processed_at timestamptz, processing_error text);
create index if not exists bookings_date_idx on bookings(booking_date);
create index if not exists bookings_status_idx on bookings(status);
create index if not exists vehicle_checks_vehicle_idx on vehicle_checks(vehicle_id, check_date);
create index if not exists incidents_status_idx on incidents(status);
